version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
  read-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_DATABASE="vf-read-db"
